### PR TITLE
fix(apiserver): filter VolumeState when list replicas

### LINKED ISSUE #1200: specified VolumeState filter error
An error was found in apiserver about filter specified VolumeState in GetVolumeReplicas.
There are two places need to be taken care.
1.VolumeReplicaName are not to be assigned a value, Synced and VolumeState are assigned to a specified value.
2.Synced are not to be assigned a value, VolumeReplicaName and VolumeState are assigned to a specified value.
And now in both condition, specified VolumeState are not to be filtered.

### PR DESCRIPTION
**Pull request by hikariwo**
#### What this PR does / why we need it:
fix #1200 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by SSmallMonster** [comment]
@peng9808 can you take a look? I am not sure if `VolumeState` is used in our front code, if not used, this change may cause empty response to the front.

**Comment by hikariwo** [comment]
@peng9808 would you like to review this PR?

**Comment by peng9808** [comment]
@SSmallMonster VolumeState is used in our front code

**Comment by peng9808** [comment]
@SSmallMonster VolumeState is used in our front code

**Comment by SSmallMonster** [comment]
lgtm

**Pull request merged**
