### PR TITLE
check for the hwameistor rclone job before processing

### PR DESCRIPTION
**Pull request by sun7927**

### CODE REVIEW

**Review by SSmallMonster — COMMENTED** [review]
LGTM

**Comment by SSmallMonster** [comment]
fix #592

**Comment by panpan0000** [comment]
should the SharedInformerFactory limit in hwameistor namespace instead of all-namespace by default? 

image

**Comment by SSmallMonster** [comment]
> should the SharedInformerFactory limit in hwameistor namespace instead of all-namespace by default?
> 
> image

Sounds Good. I will raise a PR to watch only target NameSpace instead of watching all :-)

**Pull request merged**
