### PR TITLE
Modify the document information

### PR DESCRIPTION
**Pull request by Seaiii**
#### What this PR does / why we need it:
Modify the document information
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by SSmallMonster** [comment]
@Seaiii Thanks for your contribution. This change is good for me, can you also modify the relevant Chinese docs to keep same with the English.

**Chinese Docs:**
* ./docs/i18n/cn/docusaurus-plugin-content-docs/current/architecture/modules/ldm.md

**Comment by Seaiii** [comment]
> @Seaiii Thanks for your contribution. This change is good for me, can you also modify the relevant Chinese docs to keep same with the English.

Changed.
This document doesn't look so comprehensive though.

**Comment by SSmallMonster** [comment]
Yes. We are happy to accept new documents, especially those that we do not currently cover.

**Comment by Seaiii** [comment]
> Yes. We are happy to accept new documents, especially those that we do not currently cover.

I can help with anything you need. Not only for documentation, but also for source code

**Comment by SSmallMonster** [comment]
> > Yes. We are happy to accept new documents, especially those that we do not currently cover.
> 
> I can help with anything you need. Not only for documentation, but also for source code

Wow, We have some functions in Roadmap and some problems recorded in [issues](https://github.com/hwameistor/hwameistor/issues) (including [hwameistor-operator](https://github.com/hwameistor/hwameistor-operator)). If you are interested in any issues, you can comment on the related issues below.

Thank you for your interest in our project!

**Comment by Seaiii** [comment]
> Wow, We have some functions in Roadmap and some problems recorded in [issues](https://github.com/hwameistor/hwameistor/issues) (including [hwameistor-operator](https://github.com/hwameistor/hwameistor-operator)). If you are interested in any issues, you can comment on the related issues below.


Okay, I'll fix them when I have time

**Comment by SSmallMonster** [comment]
LGTM

**Pull request merged**
