### PR TITLE
[unit-test] add more test for localDiskVolume

### PR DESCRIPTION
**Pull request by hikariwo**
#### What this PR does / why we need it:
add more test for localDiskVolume
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by hikariwo** [comment]
@peng9808 can you have a look?

**Comment by buffalo1024** [comment]
lgtm

**Comment by peng9808** [comment]
lgtm

**Comment by peng9808** [comment]
lgtm

**Review by SSmallMonster — APPROVED** [review]

**Pull request merged**
